version: '3.8'

services:
  backend:
    build:
      context: ./go-server
    ports:
      - "8080:8080"
    volumes:
      - ./go-server:/app
    networks:
      - client1-network

  frontend-1:
    build:
      context: ./client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - client1-network
    depends_on:
      - backend

  frontend-2:
    build:
      context: ./client
    env_file:
      - ./client/.env
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - client2-network
    depends_on:
      - backend

networks:
  client1-network:
  client2-network:
