version: "3.8"

services:
  router:
    image: scrapper-router-image:latest
    container_name: router
    build:
      context: ./router
    volumes:
      - ./router:/app
    networks:
      scrapper-server-network:
        ipv4_address: 10.0.10.254
      scrapper-client-network:
        ipv4_address: 10.0.11.254
    cap_add:
      - NET_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1

# PORT=8080
# APP_ENV=local

# BLUEPRINT_DB_HOST=mongo_bp
# BLUEPRINT_DB_PORT=
# BLUEPRINT_DB_USERNAME=melkey
# BLUEPRINT_DB_ROOT_PASSWORD=password1234

  backend:
    restart: unless-stopped
    image: scrapper-backend-image:latest
    container_name: backend1
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    networks:
      scrapper-server-network:
        ipv4_address: 10.0.10.2
    cap_add:
      - NET_ADMIN
    privileged: true
    environment:
      BLUEPRINT_DB_HOST: mongo
      BLUEPRINT_DB_PORT: 27017
      BLUEPRINT_DB_USER: melkey
      BLUEPRINT_DB_PASSWORD: password1234
      BLUEPRINT_DB_NAME: mongo_bp
      PORT: 8080
      TASK_QUEUE_SIZE: 10
      NUM_WORKERS: 5
 
    depends_on:
      mongo_bp:
        condition: service_healthy

  mongo_bp:
    restart: unless-stopped
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: melkey
      MONGO_INITDB_ROOT_PASSWORD: password1234
      MONGO_INITDB_DATABASE: mongo_bp
    ports:
      - "27017:27017"
    volumes:
      - mongo_volume_bp:/data/db
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    command: mongod --quiet --logpath /dev/null  # Desactiva logs
    networks:
      scrapper-server-network:
        ipv4_address: 10.0.10.3
        aliases:
        - mongo

  frontend:
    image: scrapper-client-image:latest
    container_name: frontend1
    build:
      context: ./client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      scrapper-client-network:
        ipv4_address: 10.0.11.2
    cap_add:
      - NET_ADMIN
    privileged: true
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://10.0.10.2:8080

networks:
  scrapper-server-network:
    ipam:
      config:
        - subnet: 10.0.10.0/24
  scrapper-client-network:
    ipam:
      config:
        - subnet: 10.0.11.0/24

volumes:
  mongo_volume_bp:



