version: "3.8"

services:
  router:
    image: scrapper-router-image:latest
    container_name: router
    build:
      context: ./router
    volumes:
      - ./router:/app
    networks:
      scrapper-server-network:
        ipv4_address: 10.0.10.254
      scrapper-client-network:
        ipv4_address: 10.0.11.254
    cap_add:
      - NET_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1

  backend:
    image: scrapper-server-image:latest
    container_name: backend
    build:
      context: ./scrapper_server
    ports:
      - "8080:8080"
    volumes:
      - ./scrapper_server:/app
    networks:
      scrapper-server-network:
        ipv4_address: 10.0.10.2
    cap_add:
      - NET_ADMIN
    privileged: true
    environment:
      BLUEPRINT_DB_HOST: mongo
      BLUEPRINT_DB_PORT: 28017
      BLUEPRINT_DB_USER: myuser
      BLUEPRINT_DB_PASSWORD: mypassword
      BLUEPRINT_DB_NAME: mydb
      PORT: 8080
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: scrapper-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo-data:/data/db
    ports:
      - "28017:27017"
    networks:
      scrapper-server-network:
        ipv4_address: 10.0.10.3

  frontend:
    image: scrapper-client-image:latest
    container_name: frontend1
    build:
      context: ./client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      scrapper-client-network:
        ipv4_address: 10.0.11.2
    cap_add:
      - NET_ADMIN
    privileged: true
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://10.0.10.2:8080

networks:
  scrapper-server-network:
    ipam:
      config:
        - subnet: 10.0.10.0/24
  scrapper-client-network:
    ipam:
      config:
        - subnet: 10.0.11.0/24

volumes:
  mongo-data:
