services:
  router:
    build:
      context: ./router
    volumes:
      - ./router:/app
    networks:
      server-network:
        ipv4_address: 10.0.10.254
      client-network:
        ipv4_address: 10.0.11.254
    cap_add:
      - NET_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
  backend:
    build:
      context: ./go-server
    ports:
      - "8080:8080"
    volumes:
      - ./go-server:/app
    networks:
      server-network:
        ipv4_address: 10.0.10.2

  frontend-1:
    build:
      context: ./client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      client-network:
        ipv4_address: 10.0.11.2
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://10.0.10.2:8080

  frontend-2:
    build:
      context: ./client
    env_file:
      - ./client/.env
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      client-network:
        ipv4_address: 10.0.11.3
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://10.0.11.2:8080

networks:
  server-network:
    ipam:
      config:
        - subnet: 10.0.10.0/24
  client-network:
    ipam:
      config:
        - subnet: 10.0.11.0/24
