version: '3.8'

services:
  router:
    image: scrapper-router-image:latest
    container_name: scrapper-router
    build:
      context: ./router
    volumes:
      - ./router:/app
    networks:
      scrapper-server-network:
        ipv4_address: 10.0.10.254
      scrapper-client-network:
        ipv4_address: 10.0.11.254
    cap_add:
      - NET_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1

networks:
  scrapper-server-network:
    name: scrapper-server-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24
  scrapper-client-network:
    name: scrapper-client-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.11.0/24
