services:
  frontend:
    image: scrapper-client-image:latest
    container_name: frontend1 # for new clients, increment the number
    build:
      context: ./client
    env_file:
      - ./client/.env
    ports:
      - "3000-4000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      scrapper-client-network:
        ipv4_address: 10.0.11.2 # for new client change ip address
    cap_add:
      - NET_ADMIN
    privileged: true
    environment:
      NEXT_PUBLIC_API_URL: http://10.0.10.2:8080
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  scrapper-client-network:
    external: true
