services:
  router:
    image: scrapper-router-image:latest
    container_name: router
    build:
      context: ./router
    volumes:
      - ./router:/app
    networks:
      scrapper-server-network:
        ipv4_address: 10.0.10.254
      scrapper-client-network:
        ipv4_address: 10.0.11.254
    cap_add:
      - NET_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1

  backend:
    image: scrapper-server-image:latest
    container_name: backend
    build:
      context: ./go-server
    ports:
      - "8080:8080"
    volumes:
      - ./go-server:/app
    networks:
      scrapper-server-network:
        ipv4_address: 10.0.10.2
    cap_add:
      - NET_ADMIN
    privileged: true

  frontend:
    image: scrapper-client-image:latest
    container_name: frontend1
    build:
      context: ./client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      scrapper-client-network:
        ipv4_address: 10.0.11.2
    cap_add:
      - NET_ADMIN
    privileged: true
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://10.0.10.2:8080

networks:
  scrapper-server-network:
    ipam:
      config:
        - subnet: 10.0.10.0/24
  scrapper-client-network:
    ipam:
      config:
        - subnet: 10.0.11.0/24
