version: '3.8'

services:
  router:
    build:
      context: ./router
    networks:
      backend-network:
        ipv4_address: 10.0.10.254
      client-network:
        ipv4_address: 10.0.11.254
    cap_add:
      - NET_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1

  backend:
    build:
      context: ./go-server
    ports:
      - "8080:8080"
    networks:
      backend-network:
        ipv4_address: 10.0.10.2
    depends_on:
      - router
    cap_add:
      - NET_ADMIN

  frontend1:
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      client-network:
        ipv4_address: 10.0.11.2
    depends_on:
      - backend
    cap_add:
      - NET_ADMIN

  frontend2:
    build:
      context: ./client
    ports:
      - "3001:3000"
    networks:
      client-network:
        ipv4_address: 10.0.11.3
    depends_on:
      - backend
    cap_add:
      - NET_ADMIN

networks:
  backend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24
  client-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.11.0/24
