services:
  backend:
    build:
      context: ./go-server
    ports:
      - "8080:8080"
    volumes:
      - ./go-server:/app
    networks:
      client1-network:
        ipv4_address: 172.20.0.2
      client2-network:
        ipv4_address: 172.21.0.2

  frontend-1:
    build:
      context: ./client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      client1-network:
        ipv4_address: 172.20.0.3
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://172.20.0.2:8080

  frontend-2:
    build:
      context: ./client
    env_file:
      - ./client/.env
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      client2-network:
        ipv4_address: 172.21.0.3
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://172.21.0.2:8080

networks:
  client1-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
  client2-network:
    ipam:
      config:
        - subnet: 172.21.0.0/16
